-- Storage bucket for keyframes
-- Crear en Supabase Dashboard: Storage -> New bucket -> name: keyframes, Public: true
-- O vía SQL (si tienes acceso a storage.buckets):
-- insert into storage.buckets (id, name, public) values ('keyframes', 'keyframes', true);
